name: Easy Sum CI

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    
uses: actions/checkout@v4

    
name: Compile
    run: gcc sum.c test.c -o sum_app

    
name: Test
    run: ./sum_app

    
name: Deploy (Fake)
    env:
      DEPLOY_API_KEY: ${{ secrets.DEPLOY_API_KEY }}
    run: echo "Deploying using API key: $DEPLOY_API_KEY"
