name: Easy Sum CI/CD

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile
        run: gcc sum.c test.c -o sum_app

      - name: Test
        run: ./sum_app

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sum_app
          path: sum_app

      - name: Deploy Fake
        env:
          DEPLOY_API_KEY: ${{ secrets.DEPLOY_API_KEY }}
        run: |
          echo "Deploying using API key: $DEPLOY_API_KEY"
